import { event,issue,type Run } from './model';
const unsafePath=/(?:^|[\/_?&=-])(logout|signout|delete|remove|destroy|checkout|purchase|unsubscribe|revoke|payment)(?:[\/_?&=.-]|$)/i;
export function normalizeTarget(value:string){let u:URL;try{u=new URL(value)}catch{throw new Error('Enter a complete URL starting with https://.')}if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw new Error('Use an HTTP or HTTPS URL without embedded credentials.');const h=u.hostname.toLowerCase().replace(/\.$/,'');if(!h.includes('.')||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||h.endsWith('.test')||/^[\d.]+$/.test(h)||h.includes(':')||h.includes('[')||h==='metadata.google.internal')throw new Error('Use a public website hostname. Private addresses are not supported.');if(u.port&&!['80','443'].includes(u.port))throw new Error('Only standard web ports are supported.');if(unsafePath.test(u.pathname+u.search))throw new Error('Choose a product page without destructive or payment actions.');u.hash='';return u.href;}
function privateIP(ip:string){if(ip.includes(':'))return !/^[23][0-9a-f]{3}:/i.test(ip)||/^2001:(?:0|db8|10|2):/i.test(ip);const [a,b]=ip.split('.').map(Number);return a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&[0,168].includes(b)||a===100&&b>=64&&b<=127||a===198&&[18,19,51].includes(b)||a===203&&b===0;}
async function publicHost(url:string){for(const type of ['A','AAAA']){const r=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent(new URL(url).hostname)+'&type='+type,{headers:{accept:'application/dns-json'},signal:AbortSignal.timeout(6000)});if(!r.ok)throw new Error('Could not verify the target hostname.');const d=await r.json() as {Answer?:{type:number;data:string}[]};if(d.Answer?.some(a=>[1,28].includes(a.type)&&privateIP(a.data)))throw new Error('The target resolves to a private or reserved address.');}}
async function boundedText(r:Response){if(Number(r.headers.get('content-length')||0)>1000000)throw new Error('Page exceeds the 1 MB scan limit.');const reader=r.body?.getReader();if(!reader)return '';let bytes=0;const chunks:Uint8Array[]=[];while(true){const v=await reader.read();if(v.done)break;bytes+=v.value.byteLength;if(bytes>1000000){await reader.cancel();throw new Error('Page exceeds the 1 MB scan limit.')}chunks.push(v.value)}const out=new Uint8Array(bytes);let n=0;chunks.forEach(c=>{out.set(c,n);n+=c.length});return new TextDecoder().decode(out);}
export async function auditStep(run:Run){const target=run.queue.shift();if(!target){run.status='Completed';return run}const started=Date.now();let url=normalizeTarget(target);let response:Response|undefined;
 for(let n=0;n<4;n++){await publicHost(url);response=await fetch(url,{redirect:'manual',headers:{'user-agent':'TraceQA/1.0 (+read-only document audit)','accept':'text/html'},signal:AbortSignal.timeout(12000)});if(response.status>=300&&response.status<400){const location=response.headers.get('location');await response.body?.cancel();if(!location)throw new Error('Redirect has no destination.');url=normalizeTarget(new URL(location,url).href);if(new URL(url).origin!==new URL(run.url).origin)throw new Error('Redirect leaves the selected origin. Use the final website URL.');if(n===3)throw new Error('Too many redirects.')}else break;}
 if(!response)throw new Error('No response from target.');const html=await boundedText(response);const isHtml=(response.headers.get('content-type')||'').includes('text/html');let title='';const links:string[]=[];let unlabeled=0,missingAlt=0;const labelIds=new Set<string>();const inputs:{id:string;named:boolean}[]=[];
 if(isHtml){const parsed=new HTMLRewriter().on('title',{text(t){title+=t.text}}).on('a[href]',{element(e){const h=e.getAttribute('href');if(h){try{const u=normalizeTarget(new URL(h,url).href);if(new URL(u).origin===new URL(run.url).origin&&!/\.(?:png|jpg|jpeg|svg|pdf|zip|mp4|css|js|woff2?)(?:$|\?)/i.test(u))links.push(u)}catch{}}}}).on('label[for]',{element(e){labelIds.add(e.getAttribute('for')||'')}}).on('input',{element(e){if(!['hidden','submit','button','reset','image'].includes(e.getAttribute('type')||''))inputs.push({id:e.getAttribute('id')||'',named:!!(e.getAttribute('aria-label')||e.getAttribute('aria-labelledby')||e.getAttribute('title'))})}}).on('img',{element(e){if(!e.hasAttribute('alt')&&!e.hasAttribute('aria-label')&&e.getAttribute('role')!=='presentation')missingAlt++}}).transform(new Response(html));await parsed.text();unlabeled=inputs.filter(i=>!i.named&&!labelIds.has(i.id)).length;}
 const route=new URL(url).pathname;run.pages.push({url,title:title.trim()||route,status:response.status,links:new Set(links).size,duration:Date.now()-started});run.actions++;run.events.push(event('Checked '+route,'HTTP '+response.status+' · '+new Set(links).size+' internal links',response.status>=400?'warning':'normal'));
 const add=(title:string,severity:'High'|'Medium'|'Low',type:string,description:string,expected:string,actual:string)=>{run.issues.push(issue({title,route:url,severity,type,persona:run.persona,description,steps:['Open '+url,'Inspect the document response and markup.'],expected,actual}));};
 if(response.status>=400)add('Page returned HTTP '+response.status,response.status>=500?'High':'Medium','HTTP error','The document request returned an error. Authentication or anti-bot protection can also cause this result.','A successful response or an intentional sign-in redirect.','HTTP '+response.status);
 else if(isHtml){if(!title.trim())add('Page title is missing','Low','Accessibility','The initial HTML does not include a non-empty page title. Verify after client-side rendering.','A descriptive document title.','No title found in the fetched HTML.');if(unlabeled)add('Review '+unlabeled+' possibly unlabeled input'+(unlabeled>1?'s':''),'Medium','Accessibility','Static markup check; implicit labels and client rendering require browser verification.','Each input has a programmatic accessible name.',unlabeled+' inputs lack an explicit label in the initial HTML.');if(missingAlt)add(missingAlt+' image'+(missingAlt>1?'s':'')+' missing alt attributes','Low','Accessibility','Images in the initial HTML have no alt attribute. Browser verification is recommended.','Images have meaningful alternatives or empty alt for decorative content.',missingAlt+' images without an alt attribute.');}
 const known=new Set([...run.pages.map(p=>p.url),...run.queue,target]);for(const link of links){if(!known.has(link)&&run.queue.length<80){run.queue.push(link);known.add(link)}}if(run.pages.length>=run.maxPages||!run.queue.length){run.status='Completed';run.events.push(event('Document audit complete',run.pages.length+' pages checked · '+run.issues.length+' findings','success'))}run.coverage=run.pages.length+' checked / '+(run.pages.length+run.queue.length)+' discovered pages';return run;}
