import {event,issue,type Run} from './model';
function wait(ms:number,signal:AbortSignal){return new Promise<void>((resolve,reject)=>{if(signal.aborted)return reject(new DOMException('Stopped','AbortError'));const abort=()=>{clearTimeout(t);reject(new DOMException('Stopped','AbortError'))};const t=setTimeout(()=>{signal.removeEventListener('abort',abort);resolve()},ms);signal.addEventListener('abort',abort,{once:true})})}
export async function runDemo(initial:Run,frame:HTMLIFrameElement,onUpdate:(run:Run)=>Promise<void>,signal:AbortSignal){let run=structuredClone(initial);const pages=run.persona==='First-time user'?['dashboard','projects','help','team','settings']:run.persona==='Power user'?['projects','settings','team','dashboard','help']:['projects','team','help','settings','dashboard'];const started=Date.now();
 async function navigate(name:string){if(signal.aborted)throw new DOMException('Stopped','AbortError');await new Promise<void>((resolve,reject)=>{let timeout:ReturnType<typeof setTimeout>;const clean=()=>{clearTimeout(timeout);frame.removeEventListener('load',loaded);signal.removeEventListener('abort',abort)};const loaded=()=>{clean();resolve()};const abort=()=>{clean();reject(new DOMException('Stopped','AbortError'))};frame.addEventListener('load',loaded,{once:true});signal.addEventListener('abort',abort,{once:true});timeout=setTimeout(()=>{clean();reject(new Error('The sandbox did not load. Try again.'))},12000);const link=frame.contentDocument?.querySelector<HTMLAnchorElement>('a[href="?page='+name+'"]');if(link){link.click();run.actions++;run.events.push(event('Clicked '+(name==='help'?'Help center':name),'Followed a link in the product navigation.'))}else frame.src='/api/demo?page='+name;});await wait(300,signal);}
 for(const name of pages.slice(0,run.maxPages)){await navigate(name);const doc=frame.contentDocument,win=frame.contentWindow;if(!doc||!win)throw new Error('Could not access the sandbox.');const path='/'+name;run.actions++;run.events.push(event('Exploring '+path,'Reading the page and discovering available actions.'));await onUpdate(structuredClone(run));for(let p=1;p<=2;p++){win.scrollTo({top:doc.body.scrollHeight*p/2,behavior:'smooth'});run.actions++;await wait(450,signal)}run.events.push(event('Scrolled '+path,'Scrolled to the bottom and checked the visible content.'));win.scrollTo({top:0,behavior:'smooth'});await wait(350,signal);
 const response=await fetch('/api/demo?page='+name,{signal});const status=response.status;await response.body?.cancel();const links=doc.querySelectorAll('a[href]').length;run.pages.push({url:path,title:doc.title,status,links,duration:Date.now()-started});
 if(status>=400){run.issues.push(issue({title:'Help center link returns a 404',route:path,severity:'Medium',type:'Broken link',persona:run.persona,description:'The agent clicked the Help center link and reached a missing page.',steps:['Open the Orbit sandbox.','Click Help center in the sidebar.'],expected:'The help center loads.',actual:'HTTP 404. The page shows “Page not found”.'}));run.events.push(event('Found a broken link','Help center returned HTTP 404.','warning'));}
 for(const input of doc.querySelectorAll('input')){if(input.type==='hidden')continue;const name=input.getAttribute('aria-label')||input.getAttribute('aria-labelledby')||input.getAttribute('title')||input.labels?.[0]?.textContent;if(!name){run.issues.push(issue({title:'Search input has no accessible label',route:path,severity:'Medium',type:'Accessibility',persona:run.persona,description:'The rendered search input has no programmatic label.',steps:['Open Projects.','Inspect the search input’s accessible name.'],expected:'The search input has an accessible name.',actual:input.outerHTML}));run.events.push(event('Found an unlabeled input','Search projects has no accessible name.','warning'));}}
 for(const button of doc.querySelectorAll<HTMLButtonElement>('[data-safe-action]')){const errors:string[]=[];const listen=(e:ErrorEvent)=>{errors.push(e.message)};win.addEventListener('error',listen);button.scrollIntoView({block:'center',behavior:'smooth'});await wait(250,signal);button.click();run.actions++;await wait(500,signal);win.removeEventListener('error',listen);run.events.push(event('Clicked “'+button.textContent?.trim()+'”',errors.length?errors[0]:'The action completed without a JavaScript error.',errors.length?'error':'normal'));if(errors.length)run.issues.push(issue({title:'Export button fails silently',route:path,severity:'High',type:'Functionality',persona:run.persona,description:'Clicking the export button caused a JavaScript exception. No export was produced.',steps:['Open Projects.','Click Export projects.','Observe the JavaScript error.'],expected:'A project CSV downloads.',actual:errors.join('\n')}));}
 await onUpdate(structuredClone(run));await wait(300,signal);
 }run.status='Completed';run.coverage=run.pages.length+' / 5 sandbox pages';run.events.push(event('Report is ready',run.issues.length+' findings from '+run.actions+' browser actions.','success'));await onUpdate(run);return run;}
